### ISSUE TITLE
感觉有点意思了，哈哈～

### ISSUE THREAD

**Issue by yam-liu** [ouvens/frontend-system-map#1]
首先必须肯定前端体系总结的很赞
但刷star很没有意思啊，赞与否应该是自发的吧，这样和集赞有优惠，分享看全文，发红包看照片，app store刷榜好像没什么区别。希望开源的东西不忘初心，不要变得太功利虚荣
只是表达一下个人的看法，对事不对人 :-)

**Comment by ouvens** [comment]
![image](https://cloud.githubusercontent.com/assets/922219/12603575/e5808eca-c4ee-11e5-91d2-00e2629b89a2.png)

淡定，别当真啊，我能说是感觉有些东西没整理完吗，而且这个功利有个毛线关系~

**Comment by yam-liu** [comment]
这样说确实会比较容易让人“误解”，之前见过略委婉的说法就是“如果喜欢请star支持”。

**Comment by ouvens** [comment]
不用在意这些细节~

**Comment by yangbh** [comment]
its me, zj

**Comment by hirokith** [comment]
吃相有点难看啊……整理了一年了还没好？……

回去看清楚了再回复，不要跟风回帖

**Comment by laolai** [comment]
V2大军还有三分钟到达此战场

**Comment by lambdaq** [comment]
v2ex 观光团。

**Comment by endachao** [comment]
v2ex 观光团

**Comment by cobola** [comment]
v2ex 观光团

**Comment by ghost** [comment]
v2ex 观光团

**Comment by ouvens** [comment]
【关于某博客的诋毁申明】：本项目发布于2016年初，上线不到一周相关所有资料图都已经上线在code部分（大家从日期就可以看出来了，介绍的图比较模糊是因为压缩了，否则github页面打开非常慢）并开始慢慢积累，否则不可能只有两三个issue，你以为真的能骗过大家吗。目前的版本各内容资料一直也是齐全的，包括两个版本。之前错在不该在他人GitHub 上做宣传推广，却不料此博客主不假思索，断章取义，发文误导他人，而且诋毁此项目来宣传自己，挖出一年多以前的坟墓贴，我很无语。本人相信聪明的大家会有判断能力，希望大家自己先做深入了解，避免被人恶意误导～～

**Comment by jiji262** [comment]
v2ex 观光团
看了之后果断放弃购买，省了50块！
感谢v2ex！
感谢github！

**Comment by ouvens** [comment]
书品如人品，都进来看到这里了，那也不防看看造谣诋毁我的人，https://www.zhihu.com/question/62076882 ，意外间现在才看到，我都懒得打码了，引用别人的某条评论（还有各种评论特别有意思），我一直在想我哪里做的很不对，原来问题不在我。

![](http://7tszky.com1.z0.glb.clouddn.com/FpITWmGLr4JXaa5q9a5guz18dF0g)

世界不乏心怀叵测之人，还望朋友们有点基本的判断力，看看谁是谁非。写书是为了帮助后来者，不是随便忽悠，没有大V帮后台，我只能靠内容和对读者的价值。希望大家继续支持

**Comment by shu4i** [comment]
@ouvens 此人（phodal）人品极差。
